function barPlot(xvector1, ymatrix1)
%CREATEFIGURE(xvector1, ymatrix1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 29-Jun-2024 10:00:51

% Create figure
figure('OuterPosition',[659 175.4 575.6 512.6]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'EdgeColor','none');
set(bar1(3),'DisplayName','Beam Sweeping',...
    'FaceColor',[0.545098039215686 0.83921568627451 0.647058823529412]);
set(bar1(2),'DisplayName','Proposed Robust Design',...
    'FaceColor',[0.250980392156863 0.709803921568627 0.768627450980392]);
set(bar1(1),'DisplayName','Perfect Design (Upper Bound)',...
    'FaceColor',[0.168627450980392 0.501960784313725 0.72156862745098]);

% Create ylabel
ylabel('Effective Sum-SE (bit/s/Hz)');

% Create xlabel
xlabel('Target SE (bit/s/Hz)');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XMinorGrid','on','YMinorGrid','on','ZMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

