function cdf(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 29-Jun-2024 09:53:21

% Create figure
figure1 = figure('OuterPosition',[665 377 576 513]);

% Create axes
axes1 = axes('Position',[0.138474576271186 0.0964718614718615 0.775 0.815]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Beam Sweeping','MarkerSize',8,'LineWidth',2,...
    'Color',[0.541176470588235 0.83921568627451 0.63921568627451]);

% Create plot
plot(X2,Y2,'DisplayName','Proposed Robust Design','MarkerSize',8,'LineWidth',2,...
    'Color',[0.250980392156863 0.709803921568627 0.768627450980392]);

% Create plot
plot(X3,Y3,'DisplayName','Perfect Design (Upper Bound)','MarkerSize',8,'LineWidth',2,...
    'Color',[0.168627450980392 0.501960784313725 0.72156862745098]);

% Create ylabel
ylabel('CDF');

% Create xlabel
xlabel('Effective Sum-SE (bit/s/Hz)');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.158117437698127 0.763067098204709 0.378571420003261 0.12619047891526]);

% Create axes
axes2 = axes('Position',[0.192857142857142 0.53904761904762 0.169285714285713 0.204167583828602]);
hold(axes2,'on');

% Create plot
plot(X3,Y3,'DisplayName','Perfect Design','MarkerSize',8,'LineWidth',2,...
    'Color',[0.168627450980392 0.501960784313725 0.72156862745098]);

% Create plot
plot(X2,Y2,'DisplayName','Robust Design','MarkerSize',8,'LineWidth',2,...
    'Color',[0.250980392156863 0.709803921568627 0.768627450980392]);

% Create plot
plot(X1,Y1,'DisplayName','Beam Sweeping','MarkerSize',8,'LineWidth',2,...
    'Color',[0.117647059261799 0.196078434586525 0.560784339904785]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1.63349182089645 2.06875009247675]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-0.0114173856370288 0.20621175015312]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Create ellipse
annotation(figure1,'ellipse',...
    [0.478664672765654 0.238095238095239 0.08562104152006 0.278571428571428],'LineWidth',1);

% Create arrow
annotation(figure1,'arrow',[0.814285714285713 0.87142857142857],...
    [0.259523809523812 0.216666666666669],'HeadWidth',6,'HeadLength',6);

% Create ellipse
annotation(figure1,'ellipse',[0.875 0.824578893087524 0.050665340913582 0.0417136414881621],...
    'LineWidth',1);

% Create arrow
annotation(figure1,'arrow',[0.830357142857143 0.892857142857143],...
    [0.557142857142857 0.556190476190476],'HeadWidth',6,'HeadLength',6);

% Create arrow
annotation(figure1,'arrow',[0.401785714285714 0.462857142857143],...
    [0.395238095238097 0.394285714285714],'HeadWidth',6,'HeadLength',6);

% Create ellipse
annotation(figure1,'ellipse',...
    [0.88795038705137 0.127142857142859 0.0387051372273022 0.105142857142858],'LineWidth',1);

% Create textbox
annotation(figure1,'textbox',...
    [0.651785714285713 0.483333333333336 0.183928571428566 0.142857142857158],...
    'String',{'\gamma_k = 1 bit/s/Hz','satisfied for','both users'},...
    'HorizontalAlignment','center',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.146428571428571 0.214285714285716 0.276785714285714 0.269155649738092],...
    'String',{'Inability to manage','interference often','results in SE_1 \approx \gamma_k','while SE_2 \approx 0'},...
    'LineWidth',1,...
    'HorizontalAlignment','center',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create arrow
annotation(figure1,'arrow',[0.771428571428571 0.856785714285714],...
    [0.860952380952381 0.857619047619048],'HeadWidth',6,'HeadLength',6);

% Create textbox
annotation(figure1,'textbox',...
    [0.539285714285712 0.764285714285723 0.237500000000001 0.14153660211903],...
    'String',{'Target SEs not','satisfied over 92%','of the time'},...
    'LineWidth',1,...
    'HorizontalAlignment','center',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.584285714285714 0.200952380952386 0.234999999999998 0.14153660211903],...
    'String',{'Target SEs not','satisfied less than','10% of the time'},...
    'LineWidth',1,...
    'HorizontalAlignment','center',...
    'FitBoxToText','off',...
    'EdgeColor','none');

